spring:
  application:
    name: store
    
#configurações para a aplicação store se registrar no eureka server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/