server:
  port: 8081

spring:
  application:
    name: supplier
      
#configurações para a aplicação supplier se registrar no eureka server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/